// <auto-generated />
namespace RecipeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class recipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recipe));
        
        string IMigrationMetadata.Id
        {
            get { return "202203261615501_recipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
